---

- name: packages are installed
  apt:
    name: 9mount
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: mountpoint exists
  file: path="{{mountpoint}}" state=directory

- name: fstab entry exists
  mount: 
    name: "{{mountpoint}}"
    src: "UUID={{uuid}}"
    fstype: "{{fstype}}"
    opts: "{{opts}}"
    state: "mounted"
  when: uuid is defined

- name: fstab entry exists
  mount: 
    name: "{{mountpoint}}"
    src: "{{source}}"
    fstype: "{{fstype}}"
    opts: "{{opts}}"
    state: "mounted"
  when: source is defined

- name: 9p modules are loaded during boot of Debian/Ubuntu
  lineinfile:
    dest: /etc/initramfs-tools/modules
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - 9p
    - 9pnet
    - 9pnet_virtio
  notify: update initramfs
  when: (fstype == '9p') and ((ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu'))
